language: java
jdk:
    -openjdk8
    
addons:
    sonarcloud:
        organization: marcomarcucci30
        token: e92578a3dd5ed11231eef563b837295a06cb9091
script:
    - ant build
    - sonar-scanner